/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyaratRouteImport } from './routes/syarat'
import { Route as PrivasiRouteImport } from './routes/privasi'
import { Route as PesananRouteImport } from './routes/pesanan'
import { Route as NotifikasiRouteImport } from './routes/notifikasi'
import { Route as MasukRouteImport } from './routes/masuk'
import { Route as KeranjangRouteImport } from './routes/keranjang'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CariRouteImport } from './routes/cari'
import { Route as BantuanRouteImport } from './routes/bantuan'
import { Route as BandingkanRouteImport } from './routes/bandingkan'
import { Route as AkunRouteImport } from './routes/akun'
import { Route as AdminPanenkuRouteImport } from './routes/admin-panenku'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PetaniIndexRouteImport } from './routes/petani.index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as AdminPanenkuIndexRouteImport } from './routes/admin-panenku.index'
import { Route as TokoFarmerIdRouteImport } from './routes/toko.$farmerId'
import { Route as ProdukIdRouteImport } from './routes/produk.$id'
import { Route as PetaniTarikDanaRouteImport } from './routes/petani.tarik-dana'
import { Route as PetaniTambahProdukRouteImport } from './routes/petani.tambah-produk'
import { Route as PetaniSertifikatRouteImport } from './routes/petani.sertifikat'
import { Route as PetaniProdukRouteImport } from './routes/petani.produk'
import { Route as PetaniEdukasiRouteImport } from './routes/petani.edukasi'
import { Route as PetaniDiskonRouteImport } from './routes/petani.diskon'
import { Route as PetaniBeliRouteImport } from './routes/petani.beli'
import { Route as PesananIdRouteImport } from './routes/pesanan.$id'
import { Route as ChatRoomIdRouteImport } from './routes/chat.$roomId'
import { Route as AdminPanenkuWithdrawalsRouteImport } from './routes/admin-panenku.withdrawals'
import { Route as AdminPanenkuVerifikasiRouteImport } from './routes/admin-panenku.verifikasi'
import { Route as AdminPanenkuStatistikRouteImport } from './routes/admin-panenku.statistik'
import { Route as AdminPanenkuSecurityRouteImport } from './routes/admin-panenku.security'
import { Route as AdminPanenkuReturnsRouteImport } from './routes/admin-panenku.returns'
import { Route as AdminPanenkuLogRouteImport } from './routes/admin-panenku.log'
import { Route as AdminPanenkuDiskonRouteImport } from './routes/admin-panenku.diskon'
import { Route as AdminPanenkuBiayaRouteImport } from './routes/admin-panenku.biaya'
import { Route as PetaniProdukIdRouteImport } from './routes/petani.produk.$id'
import { Route as PesananIdScanConfirmRouteImport } from './routes/pesanan.$id.scan-confirm'

const SyaratRoute = SyaratRouteImport.update({
  id: '/syarat',
  path: '/syarat',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivasiRoute = PrivasiRouteImport.update({
  id: '/privasi',
  path: '/privasi',
  getParentRoute: () => rootRouteImport,
} as any)
const PesananRoute = PesananRouteImport.update({
  id: '/pesanan',
  path: '/pesanan',
  getParentRoute: () => rootRouteImport,
} as any)
const NotifikasiRoute = NotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const MasukRoute = MasukRouteImport.update({
  id: '/masuk',
  path: '/masuk',
  getParentRoute: () => rootRouteImport,
} as any)
const KeranjangRoute = KeranjangRouteImport.update({
  id: '/keranjang',
  path: '/keranjang',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CariRoute = CariRouteImport.update({
  id: '/cari',
  path: '/cari',
  getParentRoute: () => rootRouteImport,
} as any)
const BantuanRoute = BantuanRouteImport.update({
  id: '/bantuan',
  path: '/bantuan',
  getParentRoute: () => rootRouteImport,
} as any)
const BandingkanRoute = BandingkanRouteImport.update({
  id: '/bandingkan',
  path: '/bandingkan',
  getParentRoute: () => rootRouteImport,
} as any)
const AkunRoute = AkunRouteImport.update({
  id: '/akun',
  path: '/akun',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanenkuRoute = AdminPanenkuRouteImport.update({
  id: '/admin-panenku',
  path: '/admin-panenku',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetaniIndexRoute = PetaniIndexRouteImport.update({
  id: '/petani/',
  path: '/petani/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanenkuIndexRoute = AdminPanenkuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPanenkuRoute,
} as any)
const TokoFarmerIdRoute = TokoFarmerIdRouteImport.update({
  id: '/toko/$farmerId',
  path: '/toko/$farmerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukIdRoute = ProdukIdRouteImport.update({
  id: '/produk/$id',
  path: '/produk/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PetaniTarikDanaRoute = PetaniTarikDanaRouteImport.update({
  id: '/petani/tarik-dana',
  path: '/petani/tarik-dana',
  getParentRoute: () => rootRouteImport,
} as any)
const PetaniTambahProdukRoute = PetaniTambahProdukRouteImport.update({
  id: '/petani/tambah-produk',
  path: '/petani/tambah-produk',
  getParentRoute: () => rootRouteImport,
} as any)
const PetaniSertifikatRoute = PetaniSertifikatRouteImport.update({
  id: '/petani/sertifikat',
  path: '/petani/sertifikat',
  getParentRoute: () => rootRouteImport,
} as any)
const PetaniProdukRoute = PetaniProdukRouteImport.update({
  id: '/petani/produk',
  path: '/petani/produk',
  getParentRoute: () => rootRouteImport,
} as any)
const PetaniEdukasiRoute = PetaniEdukasiRouteImport.update({
  id: '/petani/edukasi',
  path: '/petani/edukasi',
  getParentRoute: () => rootRouteImport,
} as any)
const PetaniDiskonRoute = PetaniDiskonRouteImport.update({
  id: '/petani/diskon',
  path: '/petani/diskon',
  getParentRoute: () => rootRouteImport,
} as any)
const PetaniBeliRoute = PetaniBeliRouteImport.update({
  id: '/petani/beli',
  path: '/petani/beli',
  getParentRoute: () => rootRouteImport,
} as any)
const PesananIdRoute = PesananIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PesananRoute,
} as any)
const ChatRoomIdRoute = ChatRoomIdRouteImport.update({
  id: '/chat/$roomId',
  path: '/chat/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanenkuWithdrawalsRoute = AdminPanenkuWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminPanenkuRoute,
} as any)
const AdminPanenkuVerifikasiRoute = AdminPanenkuVerifikasiRouteImport.update({
  id: '/verifikasi',
  path: '/verifikasi',
  getParentRoute: () => AdminPanenkuRoute,
} as any)
const AdminPanenkuStatistikRoute = AdminPanenkuStatistikRouteImport.update({
  id: '/statistik',
  path: '/statistik',
  getParentRoute: () => AdminPanenkuRoute,
} as any)
const AdminPanenkuSecurityRoute = AdminPanenkuSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminPanenkuRoute,
} as any)
const AdminPanenkuReturnsRoute = AdminPanenkuReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AdminPanenkuRoute,
} as any)
const AdminPanenkuLogRoute = AdminPanenkuLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AdminPanenkuRoute,
} as any)
const AdminPanenkuDiskonRoute = AdminPanenkuDiskonRouteImport.update({
  id: '/diskon',
  path: '/diskon',
  getParentRoute: () => AdminPanenkuRoute,
} as any)
const AdminPanenkuBiayaRoute = AdminPanenkuBiayaRouteImport.update({
  id: '/biaya',
  path: '/biaya',
  getParentRoute: () => AdminPanenkuRoute,
} as any)
const PetaniProdukIdRoute = PetaniProdukIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PetaniProdukRoute,
} as any)
const PesananIdScanConfirmRoute = PesananIdScanConfirmRouteImport.update({
  id: '/scan-confirm',
  path: '/scan-confirm',
  getParentRoute: () => PesananIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-panenku': typeof AdminPanenkuRouteWithChildren
  '/akun': typeof AkunRoute
  '/bandingkan': typeof BandingkanRoute
  '/bantuan': typeof BantuanRoute
  '/cari': typeof CariRoute
  '/checkout': typeof CheckoutRoute
  '/daftar': typeof DaftarRoute
  '/keranjang': typeof KeranjangRoute
  '/masuk': typeof MasukRoute
  '/notifikasi': typeof NotifikasiRoute
  '/pesanan': typeof PesananRouteWithChildren
  '/privasi': typeof PrivasiRoute
  '/syarat': typeof SyaratRoute
  '/admin-panenku/biaya': typeof AdminPanenkuBiayaRoute
  '/admin-panenku/diskon': typeof AdminPanenkuDiskonRoute
  '/admin-panenku/log': typeof AdminPanenkuLogRoute
  '/admin-panenku/returns': typeof AdminPanenkuReturnsRoute
  '/admin-panenku/security': typeof AdminPanenkuSecurityRoute
  '/admin-panenku/statistik': typeof AdminPanenkuStatistikRoute
  '/admin-panenku/verifikasi': typeof AdminPanenkuVerifikasiRoute
  '/admin-panenku/withdrawals': typeof AdminPanenkuWithdrawalsRoute
  '/chat/$roomId': typeof ChatRoomIdRoute
  '/pesanan/$id': typeof PesananIdRouteWithChildren
  '/petani/beli': typeof PetaniBeliRoute
  '/petani/diskon': typeof PetaniDiskonRoute
  '/petani/edukasi': typeof PetaniEdukasiRoute
  '/petani/produk': typeof PetaniProdukRouteWithChildren
  '/petani/sertifikat': typeof PetaniSertifikatRoute
  '/petani/tambah-produk': typeof PetaniTambahProdukRoute
  '/petani/tarik-dana': typeof PetaniTarikDanaRoute
  '/produk/$id': typeof ProdukIdRoute
  '/toko/$farmerId': typeof TokoFarmerIdRoute
  '/admin-panenku/': typeof AdminPanenkuIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/petani/': typeof PetaniIndexRoute
  '/pesanan/$id/scan-confirm': typeof PesananIdScanConfirmRoute
  '/petani/produk/$id': typeof PetaniProdukIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/akun': typeof AkunRoute
  '/bandingkan': typeof BandingkanRoute
  '/bantuan': typeof BantuanRoute
  '/cari': typeof CariRoute
  '/checkout': typeof CheckoutRoute
  '/daftar': typeof DaftarRoute
  '/keranjang': typeof KeranjangRoute
  '/masuk': typeof MasukRoute
  '/notifikasi': typeof NotifikasiRoute
  '/pesanan': typeof PesananRouteWithChildren
  '/privasi': typeof PrivasiRoute
  '/syarat': typeof SyaratRoute
  '/admin-panenku/biaya': typeof AdminPanenkuBiayaRoute
  '/admin-panenku/diskon': typeof AdminPanenkuDiskonRoute
  '/admin-panenku/log': typeof AdminPanenkuLogRoute
  '/admin-panenku/returns': typeof AdminPanenkuReturnsRoute
  '/admin-panenku/security': typeof AdminPanenkuSecurityRoute
  '/admin-panenku/statistik': typeof AdminPanenkuStatistikRoute
  '/admin-panenku/verifikasi': typeof AdminPanenkuVerifikasiRoute
  '/admin-panenku/withdrawals': typeof AdminPanenkuWithdrawalsRoute
  '/chat/$roomId': typeof ChatRoomIdRoute
  '/pesanan/$id': typeof PesananIdRouteWithChildren
  '/petani/beli': typeof PetaniBeliRoute
  '/petani/diskon': typeof PetaniDiskonRoute
  '/petani/edukasi': typeof PetaniEdukasiRoute
  '/petani/produk': typeof PetaniProdukRouteWithChildren
  '/petani/sertifikat': typeof PetaniSertifikatRoute
  '/petani/tambah-produk': typeof PetaniTambahProdukRoute
  '/petani/tarik-dana': typeof PetaniTarikDanaRoute
  '/produk/$id': typeof ProdukIdRoute
  '/toko/$farmerId': typeof TokoFarmerIdRoute
  '/admin-panenku': typeof AdminPanenkuIndexRoute
  '/chat': typeof ChatIndexRoute
  '/petani': typeof PetaniIndexRoute
  '/pesanan/$id/scan-confirm': typeof PesananIdScanConfirmRoute
  '/petani/produk/$id': typeof PetaniProdukIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-panenku': typeof AdminPanenkuRouteWithChildren
  '/akun': typeof AkunRoute
  '/bandingkan': typeof BandingkanRoute
  '/bantuan': typeof BantuanRoute
  '/cari': typeof CariRoute
  '/checkout': typeof CheckoutRoute
  '/daftar': typeof DaftarRoute
  '/keranjang': typeof KeranjangRoute
  '/masuk': typeof MasukRoute
  '/notifikasi': typeof NotifikasiRoute
  '/pesanan': typeof PesananRouteWithChildren
  '/privasi': typeof PrivasiRoute
  '/syarat': typeof SyaratRoute
  '/admin-panenku/biaya': typeof AdminPanenkuBiayaRoute
  '/admin-panenku/diskon': typeof AdminPanenkuDiskonRoute
  '/admin-panenku/log': typeof AdminPanenkuLogRoute
  '/admin-panenku/returns': typeof AdminPanenkuReturnsRoute
  '/admin-panenku/security': typeof AdminPanenkuSecurityRoute
  '/admin-panenku/statistik': typeof AdminPanenkuStatistikRoute
  '/admin-panenku/verifikasi': typeof AdminPanenkuVerifikasiRoute
  '/admin-panenku/withdrawals': typeof AdminPanenkuWithdrawalsRoute
  '/chat/$roomId': typeof ChatRoomIdRoute
  '/pesanan/$id': typeof PesananIdRouteWithChildren
  '/petani/beli': typeof PetaniBeliRoute
  '/petani/diskon': typeof PetaniDiskonRoute
  '/petani/edukasi': typeof PetaniEdukasiRoute
  '/petani/produk': typeof PetaniProdukRouteWithChildren
  '/petani/sertifikat': typeof PetaniSertifikatRoute
  '/petani/tambah-produk': typeof PetaniTambahProdukRoute
  '/petani/tarik-dana': typeof PetaniTarikDanaRoute
  '/produk/$id': typeof ProdukIdRoute
  '/toko/$farmerId': typeof TokoFarmerIdRoute
  '/admin-panenku/': typeof AdminPanenkuIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/petani/': typeof PetaniIndexRoute
  '/pesanan/$id/scan-confirm': typeof PesananIdScanConfirmRoute
  '/petani/produk/$id': typeof PetaniProdukIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-panenku'
    | '/akun'
    | '/bandingkan'
    | '/bantuan'
    | '/cari'
    | '/checkout'
    | '/daftar'
    | '/keranjang'
    | '/masuk'
    | '/notifikasi'
    | '/pesanan'
    | '/privasi'
    | '/syarat'
    | '/admin-panenku/biaya'
    | '/admin-panenku/diskon'
    | '/admin-panenku/log'
    | '/admin-panenku/returns'
    | '/admin-panenku/security'
    | '/admin-panenku/statistik'
    | '/admin-panenku/verifikasi'
    | '/admin-panenku/withdrawals'
    | '/chat/$roomId'
    | '/pesanan/$id'
    | '/petani/beli'
    | '/petani/diskon'
    | '/petani/edukasi'
    | '/petani/produk'
    | '/petani/sertifikat'
    | '/petani/tambah-produk'
    | '/petani/tarik-dana'
    | '/produk/$id'
    | '/toko/$farmerId'
    | '/admin-panenku/'
    | '/chat/'
    | '/petani/'
    | '/pesanan/$id/scan-confirm'
    | '/petani/produk/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/akun'
    | '/bandingkan'
    | '/bantuan'
    | '/cari'
    | '/checkout'
    | '/daftar'
    | '/keranjang'
    | '/masuk'
    | '/notifikasi'
    | '/pesanan'
    | '/privasi'
    | '/syarat'
    | '/admin-panenku/biaya'
    | '/admin-panenku/diskon'
    | '/admin-panenku/log'
    | '/admin-panenku/returns'
    | '/admin-panenku/security'
    | '/admin-panenku/statistik'
    | '/admin-panenku/verifikasi'
    | '/admin-panenku/withdrawals'
    | '/chat/$roomId'
    | '/pesanan/$id'
    | '/petani/beli'
    | '/petani/diskon'
    | '/petani/edukasi'
    | '/petani/produk'
    | '/petani/sertifikat'
    | '/petani/tambah-produk'
    | '/petani/tarik-dana'
    | '/produk/$id'
    | '/toko/$farmerId'
    | '/admin-panenku'
    | '/chat'
    | '/petani'
    | '/pesanan/$id/scan-confirm'
    | '/petani/produk/$id'
  id:
    | '__root__'
    | '/'
    | '/admin-panenku'
    | '/akun'
    | '/bandingkan'
    | '/bantuan'
    | '/cari'
    | '/checkout'
    | '/daftar'
    | '/keranjang'
    | '/masuk'
    | '/notifikasi'
    | '/pesanan'
    | '/privasi'
    | '/syarat'
    | '/admin-panenku/biaya'
    | '/admin-panenku/diskon'
    | '/admin-panenku/log'
    | '/admin-panenku/returns'
    | '/admin-panenku/security'
    | '/admin-panenku/statistik'
    | '/admin-panenku/verifikasi'
    | '/admin-panenku/withdrawals'
    | '/chat/$roomId'
    | '/pesanan/$id'
    | '/petani/beli'
    | '/petani/diskon'
    | '/petani/edukasi'
    | '/petani/produk'
    | '/petani/sertifikat'
    | '/petani/tambah-produk'
    | '/petani/tarik-dana'
    | '/produk/$id'
    | '/toko/$farmerId'
    | '/admin-panenku/'
    | '/chat/'
    | '/petani/'
    | '/pesanan/$id/scan-confirm'
    | '/petani/produk/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminPanenkuRoute: typeof AdminPanenkuRouteWithChildren
  AkunRoute: typeof AkunRoute
  BandingkanRoute: typeof BandingkanRoute
  BantuanRoute: typeof BantuanRoute
  CariRoute: typeof CariRoute
  CheckoutRoute: typeof CheckoutRoute
  DaftarRoute: typeof DaftarRoute
  KeranjangRoute: typeof KeranjangRoute
  MasukRoute: typeof MasukRoute
  NotifikasiRoute: typeof NotifikasiRoute
  PesananRoute: typeof PesananRouteWithChildren
  PrivasiRoute: typeof PrivasiRoute
  SyaratRoute: typeof SyaratRoute
  ChatRoomIdRoute: typeof ChatRoomIdRoute
  PetaniBeliRoute: typeof PetaniBeliRoute
  PetaniDiskonRoute: typeof PetaniDiskonRoute
  PetaniEdukasiRoute: typeof PetaniEdukasiRoute
  PetaniProdukRoute: typeof PetaniProdukRouteWithChildren
  PetaniSertifikatRoute: typeof PetaniSertifikatRoute
  PetaniTambahProdukRoute: typeof PetaniTambahProdukRoute
  PetaniTarikDanaRoute: typeof PetaniTarikDanaRoute
  ProdukIdRoute: typeof ProdukIdRoute
  TokoFarmerIdRoute: typeof TokoFarmerIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
  PetaniIndexRoute: typeof PetaniIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/syarat': {
      id: '/syarat'
      path: '/syarat'
      fullPath: '/syarat'
      preLoaderRoute: typeof SyaratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privasi': {
      id: '/privasi'
      path: '/privasi'
      fullPath: '/privasi'
      preLoaderRoute: typeof PrivasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesanan': {
      id: '/pesanan'
      path: '/pesanan'
      fullPath: '/pesanan'
      preLoaderRoute: typeof PesananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifikasi': {
      id: '/notifikasi'
      path: '/notifikasi'
      fullPath: '/notifikasi'
      preLoaderRoute: typeof NotifikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masuk': {
      id: '/masuk'
      path: '/masuk'
      fullPath: '/masuk'
      preLoaderRoute: typeof MasukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keranjang': {
      id: '/keranjang'
      path: '/keranjang'
      fullPath: '/keranjang'
      preLoaderRoute: typeof KeranjangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cari': {
      id: '/cari'
      path: '/cari'
      fullPath: '/cari'
      preLoaderRoute: typeof CariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bantuan': {
      id: '/bantuan'
      path: '/bantuan'
      fullPath: '/bantuan'
      preLoaderRoute: typeof BantuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bandingkan': {
      id: '/bandingkan'
      path: '/bandingkan'
      fullPath: '/bandingkan'
      preLoaderRoute: typeof BandingkanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akun': {
      id: '/akun'
      path: '/akun'
      fullPath: '/akun'
      preLoaderRoute: typeof AkunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-panenku': {
      id: '/admin-panenku'
      path: '/admin-panenku'
      fullPath: '/admin-panenku'
      preLoaderRoute: typeof AdminPanenkuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petani/': {
      id: '/petani/'
      path: '/petani'
      fullPath: '/petani/'
      preLoaderRoute: typeof PetaniIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-panenku/': {
      id: '/admin-panenku/'
      path: '/'
      fullPath: '/admin-panenku/'
      preLoaderRoute: typeof AdminPanenkuIndexRouteImport
      parentRoute: typeof AdminPanenkuRoute
    }
    '/toko/$farmerId': {
      id: '/toko/$farmerId'
      path: '/toko/$farmerId'
      fullPath: '/toko/$farmerId'
      preLoaderRoute: typeof TokoFarmerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/$id': {
      id: '/produk/$id'
      path: '/produk/$id'
      fullPath: '/produk/$id'
      preLoaderRoute: typeof ProdukIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petani/tarik-dana': {
      id: '/petani/tarik-dana'
      path: '/petani/tarik-dana'
      fullPath: '/petani/tarik-dana'
      preLoaderRoute: typeof PetaniTarikDanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petani/tambah-produk': {
      id: '/petani/tambah-produk'
      path: '/petani/tambah-produk'
      fullPath: '/petani/tambah-produk'
      preLoaderRoute: typeof PetaniTambahProdukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petani/sertifikat': {
      id: '/petani/sertifikat'
      path: '/petani/sertifikat'
      fullPath: '/petani/sertifikat'
      preLoaderRoute: typeof PetaniSertifikatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petani/produk': {
      id: '/petani/produk'
      path: '/petani/produk'
      fullPath: '/petani/produk'
      preLoaderRoute: typeof PetaniProdukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petani/edukasi': {
      id: '/petani/edukasi'
      path: '/petani/edukasi'
      fullPath: '/petani/edukasi'
      preLoaderRoute: typeof PetaniEdukasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petani/diskon': {
      id: '/petani/diskon'
      path: '/petani/diskon'
      fullPath: '/petani/diskon'
      preLoaderRoute: typeof PetaniDiskonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petani/beli': {
      id: '/petani/beli'
      path: '/petani/beli'
      fullPath: '/petani/beli'
      preLoaderRoute: typeof PetaniBeliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesanan/$id': {
      id: '/pesanan/$id'
      path: '/$id'
      fullPath: '/pesanan/$id'
      preLoaderRoute: typeof PesananIdRouteImport
      parentRoute: typeof PesananRoute
    }
    '/chat/$roomId': {
      id: '/chat/$roomId'
      path: '/chat/$roomId'
      fullPath: '/chat/$roomId'
      preLoaderRoute: typeof ChatRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-panenku/withdrawals': {
      id: '/admin-panenku/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin-panenku/withdrawals'
      preLoaderRoute: typeof AdminPanenkuWithdrawalsRouteImport
      parentRoute: typeof AdminPanenkuRoute
    }
    '/admin-panenku/verifikasi': {
      id: '/admin-panenku/verifikasi'
      path: '/verifikasi'
      fullPath: '/admin-panenku/verifikasi'
      preLoaderRoute: typeof AdminPanenkuVerifikasiRouteImport
      parentRoute: typeof AdminPanenkuRoute
    }
    '/admin-panenku/statistik': {
      id: '/admin-panenku/statistik'
      path: '/statistik'
      fullPath: '/admin-panenku/statistik'
      preLoaderRoute: typeof AdminPanenkuStatistikRouteImport
      parentRoute: typeof AdminPanenkuRoute
    }
    '/admin-panenku/security': {
      id: '/admin-panenku/security'
      path: '/security'
      fullPath: '/admin-panenku/security'
      preLoaderRoute: typeof AdminPanenkuSecurityRouteImport
      parentRoute: typeof AdminPanenkuRoute
    }
    '/admin-panenku/returns': {
      id: '/admin-panenku/returns'
      path: '/returns'
      fullPath: '/admin-panenku/returns'
      preLoaderRoute: typeof AdminPanenkuReturnsRouteImport
      parentRoute: typeof AdminPanenkuRoute
    }
    '/admin-panenku/log': {
      id: '/admin-panenku/log'
      path: '/log'
      fullPath: '/admin-panenku/log'
      preLoaderRoute: typeof AdminPanenkuLogRouteImport
      parentRoute: typeof AdminPanenkuRoute
    }
    '/admin-panenku/diskon': {
      id: '/admin-panenku/diskon'
      path: '/diskon'
      fullPath: '/admin-panenku/diskon'
      preLoaderRoute: typeof AdminPanenkuDiskonRouteImport
      parentRoute: typeof AdminPanenkuRoute
    }
    '/admin-panenku/biaya': {
      id: '/admin-panenku/biaya'
      path: '/biaya'
      fullPath: '/admin-panenku/biaya'
      preLoaderRoute: typeof AdminPanenkuBiayaRouteImport
      parentRoute: typeof AdminPanenkuRoute
    }
    '/petani/produk/$id': {
      id: '/petani/produk/$id'
      path: '/$id'
      fullPath: '/petani/produk/$id'
      preLoaderRoute: typeof PetaniProdukIdRouteImport
      parentRoute: typeof PetaniProdukRoute
    }
    '/pesanan/$id/scan-confirm': {
      id: '/pesanan/$id/scan-confirm'
      path: '/scan-confirm'
      fullPath: '/pesanan/$id/scan-confirm'
      preLoaderRoute: typeof PesananIdScanConfirmRouteImport
      parentRoute: typeof PesananIdRoute
    }
  }
}

interface AdminPanenkuRouteChildren {
  AdminPanenkuBiayaRoute: typeof AdminPanenkuBiayaRoute
  AdminPanenkuDiskonRoute: typeof AdminPanenkuDiskonRoute
  AdminPanenkuLogRoute: typeof AdminPanenkuLogRoute
  AdminPanenkuReturnsRoute: typeof AdminPanenkuReturnsRoute
  AdminPanenkuSecurityRoute: typeof AdminPanenkuSecurityRoute
  AdminPanenkuStatistikRoute: typeof AdminPanenkuStatistikRoute
  AdminPanenkuVerifikasiRoute: typeof AdminPanenkuVerifikasiRoute
  AdminPanenkuWithdrawalsRoute: typeof AdminPanenkuWithdrawalsRoute
  AdminPanenkuIndexRoute: typeof AdminPanenkuIndexRoute
}

const AdminPanenkuRouteChildren: AdminPanenkuRouteChildren = {
  AdminPanenkuBiayaRoute: AdminPanenkuBiayaRoute,
  AdminPanenkuDiskonRoute: AdminPanenkuDiskonRoute,
  AdminPanenkuLogRoute: AdminPanenkuLogRoute,
  AdminPanenkuReturnsRoute: AdminPanenkuReturnsRoute,
  AdminPanenkuSecurityRoute: AdminPanenkuSecurityRoute,
  AdminPanenkuStatistikRoute: AdminPanenkuStatistikRoute,
  AdminPanenkuVerifikasiRoute: AdminPanenkuVerifikasiRoute,
  AdminPanenkuWithdrawalsRoute: AdminPanenkuWithdrawalsRoute,
  AdminPanenkuIndexRoute: AdminPanenkuIndexRoute,
}

const AdminPanenkuRouteWithChildren = AdminPanenkuRoute._addFileChildren(
  AdminPanenkuRouteChildren,
)

interface PesananIdRouteChildren {
  PesananIdScanConfirmRoute: typeof PesananIdScanConfirmRoute
}

const PesananIdRouteChildren: PesananIdRouteChildren = {
  PesananIdScanConfirmRoute: PesananIdScanConfirmRoute,
}

const PesananIdRouteWithChildren = PesananIdRoute._addFileChildren(
  PesananIdRouteChildren,
)

interface PesananRouteChildren {
  PesananIdRoute: typeof PesananIdRouteWithChildren
}

const PesananRouteChildren: PesananRouteChildren = {
  PesananIdRoute: PesananIdRouteWithChildren,
}

const PesananRouteWithChildren =
  PesananRoute._addFileChildren(PesananRouteChildren)

interface PetaniProdukRouteChildren {
  PetaniProdukIdRoute: typeof PetaniProdukIdRoute
}

const PetaniProdukRouteChildren: PetaniProdukRouteChildren = {
  PetaniProdukIdRoute: PetaniProdukIdRoute,
}

const PetaniProdukRouteWithChildren = PetaniProdukRoute._addFileChildren(
  PetaniProdukRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminPanenkuRoute: AdminPanenkuRouteWithChildren,
  AkunRoute: AkunRoute,
  BandingkanRoute: BandingkanRoute,
  BantuanRoute: BantuanRoute,
  CariRoute: CariRoute,
  CheckoutRoute: CheckoutRoute,
  DaftarRoute: DaftarRoute,
  KeranjangRoute: KeranjangRoute,
  MasukRoute: MasukRoute,
  NotifikasiRoute: NotifikasiRoute,
  PesananRoute: PesananRouteWithChildren,
  PrivasiRoute: PrivasiRoute,
  SyaratRoute: SyaratRoute,
  ChatRoomIdRoute: ChatRoomIdRoute,
  PetaniBeliRoute: PetaniBeliRoute,
  PetaniDiskonRoute: PetaniDiskonRoute,
  PetaniEdukasiRoute: PetaniEdukasiRoute,
  PetaniProdukRoute: PetaniProdukRouteWithChildren,
  PetaniSertifikatRoute: PetaniSertifikatRoute,
  PetaniTambahProdukRoute: PetaniTambahProdukRoute,
  PetaniTarikDanaRoute: PetaniTarikDanaRoute,
  ProdukIdRoute: ProdukIdRoute,
  TokoFarmerIdRoute: TokoFarmerIdRoute,
  ChatIndexRoute: ChatIndexRoute,
  PetaniIndexRoute: PetaniIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
